///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TVPNGitDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TVPNGitDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c8181431-cfc8-42fe-beea-1d657517edb1")]
    public partial class TVPNGitDemoRepository : RepoGenBaseFolder
    {
        static TVPNGitDemoRepository instance = new TVPNGitDemoRepository();
        TVPNGitDemoRepositoryFolders.ExplorerAppFolder _explorer;
        TVPNGitDemoRepositoryFolders.RecycleBinAppFolder _recyclebin;
        TVPNGitDemoRepositoryFolders.Explorer1AppFolder _explorer1;

        /// <summary>
        /// Gets the singleton class instance representing the TVPNGitDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("c8181431-cfc8-42fe-beea-1d657517edb1")]
        public static TVPNGitDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TVPNGitDemoRepository() 
            : base("TVPNGitDemoRepository", "/", null, 0, false, "c8181431-cfc8-42fe-beea-1d657517edb1", ".\\RepositoryImages\\TVPNGitDemoRepositoryc8181431.rximgres")
        {
            _explorer = new TVPNGitDemoRepositoryFolders.ExplorerAppFolder(this);
            _recyclebin = new TVPNGitDemoRepositoryFolders.RecycleBinAppFolder(this);
            _explorer1 = new TVPNGitDemoRepositoryFolders.Explorer1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c8181431-cfc8-42fe-beea-1d657517edb1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("ad4012f9-2d2a-40db-88b2-f98cbcf3410b")]
        public virtual TVPNGitDemoRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The RecycleBin folder.
        /// </summary>
        [RepositoryFolder("cfabd703-c49e-4814-9971-391ad3864b1c")]
        public virtual TVPNGitDemoRepositoryFolders.RecycleBinAppFolder RecycleBin
        {
            get { return _recyclebin; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("6ef25fc2-06b8-4924-bc7d-6ece68cbfb64")]
        public virtual TVPNGitDemoRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TVPNGitDemoRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("ad4012f9-2d2a-40db-88b2-f98cbcf3410b")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            ExplorerInfoClass _explorerInfo;
            RecycleBinInfoClass _recyclebinInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/form[@title='']", parentFolder, 30000, null, true, "ad4012f9-2d2a-40db-88b2-f98cbcf3410b", "")
            {
                _explorerInfo = new ExplorerInfoClass(this);
                _recyclebinInfo = new RecycleBinInfoClass(this);
            }

            /// <summary>
            /// The ExplorerInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("a2ddc1f0-ce0a-41d6-a1df-5767e86bda79")]
            public class ExplorerInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ExplorerInfoClass class constructor.
                /// </summary>
                public ExplorerInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Explorer", "", 30000, null, "a2ddc1f0-ce0a-41d6-a1df-5767e86bda79")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("daf2bc3b-067a-4a68-b782-cd7e8f8a107c")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("daf2bc3b-067a-4a68-b782-cd7e8f8a107c");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("daf2bc3b-067a-4a68-b782-cd7e8f8a107c")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("daf2bc3b-067a-4a68-b782-cd7e8f8a107c", cropRect);
                }
            }

            /// <summary>
            /// The RecycleBinInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("f0bfc089-5f94-4d74-bbae-2ffa93003efd")]
            public class RecycleBinInfoClass : RepoItemInfo
            {
                /// <summary>
                /// RecycleBinInfoClass class constructor.
                /// </summary>
                public RecycleBinInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "RecycleBin", "?/?/list[@controlid='1']/listitem[@text='Recycle Bin']", 30000, null, "f0bfc089-5f94-4d74-bbae-2ffa93003efd")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("09a7df47-c89f-4b4d-8e5e-b240a434b6b2")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("09a7df47-c89f-4b4d-8e5e-b240a434b6b2");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("09a7df47-c89f-4b4d-8e5e-b240a434b6b2")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("09a7df47-c89f-4b4d-8e5e-b240a434b6b2", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("a02a682b-224f-4ecb-bdaf-0a525a73430a")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("a02a682b-224f-4ecb-bdaf-0a525a73430a");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("a02a682b-224f-4ecb-bdaf-0a525a73430a")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("a02a682b-224f-4ecb-bdaf-0a525a73430a", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ad4012f9-2d2a-40db-88b2-f98cbcf3410b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ad4012f9-2d2a-40db-88b2-f98cbcf3410b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Explorer item.
            /// </summary>
            [RepositoryItem("a2ddc1f0-ce0a-41d6-a1df-5767e86bda79")]
            public virtual Ranorex.Form Explorer
            {
                get
                {
                    return _explorerInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Explorer item info.
            /// </summary>
            [RepositoryItemInfo("a2ddc1f0-ce0a-41d6-a1df-5767e86bda79")]
            public virtual ExplorerInfoClass ExplorerInfo
            {
                get
                {
                    return _explorerInfo;
                }
            }

            /// <summary>
            /// The RecycleBin item.
            /// </summary>
            [RepositoryItem("f0bfc089-5f94-4d74-bbae-2ffa93003efd")]
            public virtual Ranorex.ListItem RecycleBin
            {
                get
                {
                    return _recyclebinInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The RecycleBin item info.
            /// </summary>
            [RepositoryItemInfo("f0bfc089-5f94-4d74-bbae-2ffa93003efd")]
            public virtual RecycleBinInfoClass RecycleBinInfo
            {
                get
                {
                    return _recyclebinInfo;
                }
            }
        }

        /// <summary>
        /// The RecycleBinAppFolder folder.
        /// </summary>
        [RepositoryFolder("cfabd703-c49e-4814-9971-391ad3864b1c")]
        public partial class RecycleBinAppFolder : RepoGenBaseFolder
        {
            MaximizeRestoreInfoClass _maximizerestoreInfo;
            RecycleBinInfoClass _recyclebinInfo;
            TitleBarInfoClass _titlebarInfo;
            CloseInfoClass _closeInfo;

            /// <summary>
            /// Creates a new RecycleBin  folder.
            /// </summary>
            public RecycleBinAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RecycleBin", "/form[@title='Recycle Bin']", parentFolder, 30000, null, true, "cfabd703-c49e-4814-9971-391ad3864b1c", "")
            {
                _maximizerestoreInfo = new MaximizeRestoreInfoClass(this);
                _recyclebinInfo = new RecycleBinInfoClass(this);
                _titlebarInfo = new TitleBarInfoClass(this);
                _closeInfo = new CloseInfoClass(this);
            }

            /// <summary>
            /// The MaximizeRestoreInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("aa879b99-caf2-41d0-9fd3-0c9b11d5e0e5")]
            public class MaximizeRestoreInfoClass : RepoItemInfo
            {
                /// <summary>
                /// MaximizeRestoreInfoClass class constructor.
                /// </summary>
                public MaximizeRestoreInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "MaximizeRestore", "?/?/button[@automationid='Maximize-Restore']", 30000, null, "aa879b99-caf2-41d0-9fd3-0c9b11d5e0e5")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("3a48d90c-8441-4029-b7fa-c5e9f9e93226")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("3a48d90c-8441-4029-b7fa-c5e9f9e93226");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("3a48d90c-8441-4029-b7fa-c5e9f9e93226")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("3a48d90c-8441-4029-b7fa-c5e9f9e93226", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("482e6c1a-84e6-45c9-8bc7-6be69b8b2185")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("482e6c1a-84e6-45c9-8bc7-6be69b8b2185");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("482e6c1a-84e6-45c9-8bc7-6be69b8b2185")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("482e6c1a-84e6-45c9-8bc7-6be69b8b2185", cropRect);
                }
            }

            /// <summary>
            /// The RecycleBinInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("1ba1baa2-3a82-4324-bba2-4e8dc7142d30")]
            public class RecycleBinInfoClass : RepoItemInfo
            {
                /// <summary>
                /// RecycleBinInfoClass class constructor.
                /// </summary>
                public RecycleBinInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "RecycleBin", "", 30000, null, "1ba1baa2-3a82-4324-bba2-4e8dc7142d30")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("6c98a3a4-67e8-4958-a09e-9978f1dfecf4")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("6c98a3a4-67e8-4958-a09e-9978f1dfecf4");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("6c98a3a4-67e8-4958-a09e-9978f1dfecf4")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("6c98a3a4-67e8-4958-a09e-9978f1dfecf4", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("afea1237-80f9-4b71-bae0-6328e7120926")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("afea1237-80f9-4b71-bae0-6328e7120926");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("afea1237-80f9-4b71-bae0-6328e7120926")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("afea1237-80f9-4b71-bae0-6328e7120926", cropRect);
                }
            }

            /// <summary>
            /// The TitleBarInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("251c6772-6c58-4fe1-a476-4bdaffedeb5b")]
            public class TitleBarInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TitleBarInfoClass class constructor.
                /// </summary>
                public TitleBarInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TitleBar", "titlebar[@automationid='TitleBar']", 30000, null, "251c6772-6c58-4fe1-a476-4bdaffedeb5b")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("74cd9bde-dba5-4402-a893-ac14b5ca8859")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("74cd9bde-dba5-4402-a893-ac14b5ca8859");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("74cd9bde-dba5-4402-a893-ac14b5ca8859")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("74cd9bde-dba5-4402-a893-ac14b5ca8859", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("6ef0c537-026a-4fb7-b68e-68ebecacadd3")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("6ef0c537-026a-4fb7-b68e-68ebecacadd3");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("6ef0c537-026a-4fb7-b68e-68ebecacadd3")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("6ef0c537-026a-4fb7-b68e-68ebecacadd3", cropRect);
                }
            }

            /// <summary>
            /// The CloseInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("47f6c0f5-9845-443f-9d08-1c215f4f9960")]
            public class CloseInfoClass : RepoItemInfo
            {
                /// <summary>
                /// CloseInfoClass class constructor.
                /// </summary>
                public CloseInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Close", "?/?/button[@automationid='Close']", 30000, null, "47f6c0f5-9845-443f-9d08-1c215f4f9960")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("d4cca4e5-774c-473b-a165-05127e655953")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("d4cca4e5-774c-473b-a165-05127e655953");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d4cca4e5-774c-473b-a165-05127e655953")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d4cca4e5-774c-473b-a165-05127e655953", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cfabd703-c49e-4814-9971-391ad3864b1c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cfabd703-c49e-4814-9971-391ad3864b1c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MaximizeRestore item.
            /// </summary>
            [RepositoryItem("aa879b99-caf2-41d0-9fd3-0c9b11d5e0e5")]
            public virtual Ranorex.Button MaximizeRestore
            {
                get
                {
                    return _maximizerestoreInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MaximizeRestore item info.
            /// </summary>
            [RepositoryItemInfo("aa879b99-caf2-41d0-9fd3-0c9b11d5e0e5")]
            public virtual MaximizeRestoreInfoClass MaximizeRestoreInfo
            {
                get
                {
                    return _maximizerestoreInfo;
                }
            }

            /// <summary>
            /// The RecycleBin item.
            /// </summary>
            [RepositoryItem("1ba1baa2-3a82-4324-bba2-4e8dc7142d30")]
            public virtual Ranorex.Form RecycleBin
            {
                get
                {
                    return _recyclebinInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The RecycleBin item info.
            /// </summary>
            [RepositoryItemInfo("1ba1baa2-3a82-4324-bba2-4e8dc7142d30")]
            public virtual RecycleBinInfoClass RecycleBinInfo
            {
                get
                {
                    return _recyclebinInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("251c6772-6c58-4fe1-a476-4bdaffedeb5b")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("251c6772-6c58-4fe1-a476-4bdaffedeb5b")]
            public virtual TitleBarInfoClass TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("47f6c0f5-9845-443f-9d08-1c215f4f9960")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("47f6c0f5-9845-443f-9d08-1c215f4f9960")]
            public virtual CloseInfoClass CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("6ef25fc2-06b8-4924-bc7d-6ece68cbfb64")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RecycleBinInfoClass _recyclebinInfo;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "6ef25fc2-06b8-4924-bc7d-6ece68cbfb64", "")
            {
                _recyclebinInfo = new RecycleBinInfoClass(this);
            }

            /// <summary>
            /// The RecycleBinInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("50d59906-26c3-4a3f-b6f6-a356d29c0bba")]
            public class RecycleBinInfoClass : RepoItemInfo
            {
                /// <summary>
                /// RecycleBinInfoClass class constructor.
                /// </summary>
                public RecycleBinInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "RecycleBin", "?/?/list[@controlid='1']/listitem[@text='Recycle Bin']", 30000, null, "50d59906-26c3-4a3f-b6f6-a356d29c0bba")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("5b7059de-e87a-4462-9aff-0631178c5e80")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("5b7059de-e87a-4462-9aff-0631178c5e80");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("5b7059de-e87a-4462-9aff-0631178c5e80")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("5b7059de-e87a-4462-9aff-0631178c5e80", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("3d3f1405-21f5-4236-b56d-4162bf38a0f1")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("3d3f1405-21f5-4236-b56d-4162bf38a0f1");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("3d3f1405-21f5-4236-b56d-4162bf38a0f1")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("3d3f1405-21f5-4236-b56d-4162bf38a0f1", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6ef25fc2-06b8-4924-bc7d-6ece68cbfb64")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6ef25fc2-06b8-4924-bc7d-6ece68cbfb64")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RecycleBin item.
            /// </summary>
            [RepositoryItem("50d59906-26c3-4a3f-b6f6-a356d29c0bba")]
            public virtual Ranorex.ListItem RecycleBin
            {
                get
                {
                    return _recyclebinInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The RecycleBin item info.
            /// </summary>
            [RepositoryItemInfo("50d59906-26c3-4a3f-b6f6-a356d29c0bba")]
            public virtual RecycleBinInfoClass RecycleBinInfo
            {
                get
                {
                    return _recyclebinInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
